# Site settings
title:            Emma
email:            ""
description:      Emma is a Scala API for scalable data analysis. The goal of Emma is to improve developer productivity by hiding parallelism aspects behind a high-level, declarative API.
baseurl:          "http://emma-language.org" # the subpath of your site, e.g. /blog/
url:              "" # the base hostname & protocol for your site
twitter_username: ""
github_username:  emmalanguage/emma

# Build settings
markdown:         kramdown
sass:
  style:          compressed
collections:
  tutorials:
    output:       true
  docs:
    output:       true
  legal:
    output:       true

defaults:
  - scope:
      path:       ""
      type:       tutorials
    values:
      layout:     tutorials
  - scope:
      path:       ""
      type:       docs
    values:
      layout:     documentation

highlighter:      pygments
